# -*- coding: utf-8 -*-
"""02. Power Rule and Chain Rule With Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5MiomTBiaJ6MVBvNTVge-LqKBNNYOaZ
"""

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return x**5 - 3*x**2 + 7

def df(x):
    return 5*x**4 - 6*x

def central_diff(f, x0, h =1e-6):
    return (f(x0+h) - f(x0-h)) / (2*h)


# Visualization
xs = np.linspace(-3, 3, 500)
plt.plot(xs, f(xs), label= "f(x)")
plt.plot(xs, df(xs), label = "df(x)")
plt.title("Power Rule: x**5 - 3*x**2 + 7")
plt.xlabel("x") # plt.xlabel() ; plt.ylabel()
plt.ylabel("value")
plt.legend()
plt.grid(True)
plt.show()

for x0 in [-3, 2, 1, 0, 1, 2, 3]:
    #print(x0)
    print(x0, central_diff(f, x0), df(x0))

